on: ['pull_request']

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
            name: build-stats
            path: index.js
